### ISSUE TITLE
Deploy to Azure button doesn't work

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/azure-saas#136]
When attempting to go through the `Deploy to Azure` button on https://azuresaas.net/, you get to the "Review and Create" button in the Azure portal and the validation fails with this error:

```
{"code":"MultipleErrorsOccurred","details":[{"code":"InvalidContentLink","message":"Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/azure-saas/main/src/Saas.OnboardingFlow/Saas.OnboardingFlow.CosmosDb.Deployment/azuredeploy.json'. The tracking Id is '5d3369dd-6212-4f2d-b838-304570b8d808'. Please see https://aka.ms/arm-deploy for usage details."},{"code":"InvalidContentLink","message":"Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/azure-saas/main/src/Saas.Data/Saas.Data.Sql.Deployment/azuredeploy.json'. The tracking Id is '5d3369dd-6212-4f2d-b838-304570b8d808'. Please see https://aka.ms/arm-deploy for usage details."}],"message":"Multiple error occurred: BadRequest,BadRequest. Please see details."}
```

It apperas to be due to a broken link for: 
* https://raw.githubusercontent.com/Azure/azure-saas/main/src/Saas.OnboardingFlow/Saas.OnboardingFlow.CosmosDb.Deployment/azuredeploy.json
* https://raw.githubusercontent.com/Azure/azure-saas/main/src/Saas.Data/Saas.Data.Sql.Deployment/azuredeploy.json

**Comment by KietNhiTran** [comment]
Encountered same problem. It looks like some projects has been cleanup from the source code.

**Comment by wanesurf** [comment]
Same here

**Comment by nickpinheiro** [comment]
Hello @lastcoolnameleft, @KietNhiTran, @wanesurf.  We are currently in the process of preparing for a soft launch at //build towards the end of this month.  As such we are migrating the existing deployment from ARM to bicep.  The current 'Deploy to Azure' button is not functional while we undergo the migration.  We plan to have the new deployment completed within the next few weeks.  Please feel free to join the Azure SaaS community as we will be sending out an email notification once complete.  https://www.azuresaas.net/join  Thank you!
