### ISSUE TITLE
Deploy button not working

### ISSUE THREAD

**Issue by wanesurf** [Azure/azure-saas#140]
{
  "code": "MultipleErrorsOccurred",
  "details": [
    {
      "code": "InvalidContentLink",
      "message": "Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/azure-saas/main/src/Saas.OnboardingFlow/Saas.OnboardingFlow.CosmosDb.Deployment/azuredeploy.json'. The tracking Id is 'cf99b363-c6d7-454e-802e-3aa691c95358'. Please see https://aka.ms/arm-deploy for usage details."
    },
    {
      "code": "InvalidContentLink",
      "message": "Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/azure-saas/main/src/Saas.Data/Saas.Data.Sql.Deployment/azuredeploy.json'. The tracking Id is 'cf99b363-c6d7-454e-802e-3aa691c95358'. Please see https://aka.ms/arm-deploy for usage details."
    }
  ],
  "message": "Multiple error occurred: BadRequest,BadRequest. Please see details."
}

**Comment by nickpinheiro** [comment]
Hello @wanesurf.  We are currently in the process of preparing for a soft launch at //build towards the end of this month.  As such we are migrating the existing deployment from ARM to bicep.  The current 'Deploy to Azure' button is not functional while we undergo the migration.  We plan to have the new deployment completed within the next few weeks.  Please feel free to join the Azure SaaS community as we will be sending out an email notification once complete.  https://www.azuresaas.net/join  Thank you!

**Comment by wanesurf** [comment]
Hello Nick,

Thank you for your answer !

Is there a way I can try it without the deployment button to try the solution ?
I would like to see if the framework is adapted to what I need to do more quickly.

Also do you know if the new version of the Saas architecture would be able to deploy a containerize micro services architecture ?

Best regards,

Helwan Mandé

On 11 May 2022, at 2:37 AM, Nick Pinheiro ***@***.***> wrote:

﻿

Hello @wanesurf<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwanesurf&data=05%7C01%7Chelwan.mande.1%40ens.etsmtl.ca%7Ca2fc5e1d9e1e4c2ec9c108da3318b334%7C70aae3b79f3b484d8f9549e8fbb783c0%7C0%7C0%7C637878478422009539%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6pjY%2F7YTcfAf5kBiMREThBexAa6xYuNUNhgFSZRsUYw%3D&reserved=0>. We are currently in the process of preparing for a soft launch at //build towards the end of this month. As such we are migrating the existing deployment from ARM to bicep. The current 'Deploy to Azure' button is not functional while we undergo the migration. We plan to have the new deployment completed within the next few weeks. Please feel free to join the Azure SaaS community as we will be sending out an email notification once complete. https://www.azuresaas.net/join<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.azuresaas.net%2Fjoin&data=05%7C01%7Chelwan.mande.1%40ens.etsmtl.ca%7Ca2fc5e1d9e1e4c2ec9c108da3318b334%7C70aae3b79f3b484d8f9549e8fbb783c0%7C0%7C0%7C637878478422009539%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7XX8ZSsIAyfmMZJ4C7UlEq9BCDVuyjgaQbFeknCfle4%3D&reserved=0> Thank you!
