### ISSUE TITLE
Clicking on "Deploy to Azure" on https://azuresaas.net/ results in an error.

### ISSUE THREAD

**Issue by MichaelSchreiber** [Azure/azure-saas#198]
**Describe the bug**
Clicking on "Deploy to Azure" on https://azuresaas.net/ results in:
There was an error downloading from URI 'https://raw.githubusercontent.com/Azure/azure-saas/main/src/Saas.Deployment/Saas.Deployment.Root/createUiDefinition.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint.
There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure/azure-saas/main/src/Saas.Deployment/Saas.Deployment.Root/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 

**To Reproduce**
1. Go to '[...](https://azuresaas.net/)'
2. Click on 'Deploy to Azure'
3. See error
Following the link https://raw.githubusercontent.com/Azure/azure-saas/main/src/Saas.Deployment/Saas.Deployment.Root/createUiDefinition.json manually results in a 404.

**Expected behavior**
The custom deployment should start.

**Screenshots**
n/a

**Desktop**
 - OS: Windows 11
 - Browser Edge
 - Version 104.0.1293.54

**Additional context**
n/a

**Comment by nickpinheiro** [comment]
Hi @MichaelSchreiber.  Thank you for your issue submission.  We have disabled the previous 'Deploy to Azure' button as we are undergoing an upgrade of the deployment process which we will release soon.  We have gone ahead and removed the button from azuresaas.net.  We will notify the community of the future deployment release via the mailing list.  Thanks!

**Comment by landonpierce** [comment]
@MichaelSchreiber Just to add to Nick's comment, the latest and greatest documentation/quick start guide can be found here with deployment instructions: https://azure.github.io/azure-saas/quick-start/
