### ISSUE TITLE
Setup Identity Framework - Docker B2C tenant creation Error Not Found Resource with ID

### ISSUE THREAD

**Issue by basztech** [Azure/azure-saas#199]
Hi,

Following the quick start guide using Docker fails early in the script on setting up the identity framework. It looks like the script is trying to validate against the wrong path. Is there a work around or do I ned to forget using Docker?

Error message....

```
Waiting for 30 seconds for B2C tenant creation...
ERROR: (NotFound) Resource with ID '*********************01/saas-identity/bastechllc.onmicrosoft.com' does not exist.
Code: NotFound
Message: Resource with ID '*********************01/saas-identity/bastechllc.onmicrosoft.com' does not exist.
Target: resource
```

My Azure resource group that was created by the script...
```
{
    "id": "/subscriptions/*********************01/resourceGroups/saas-identity",
    "name": "saas-identity",
    "location": "eastus",
    "properties": {
        "provisioningState": "Succeeded"
    }
}
```

**Comment by landonpierce** [comment]
@basztech Thanks for reporting the issue. Can you confirm (through the portal) if the B2C tenant is actually getting created within that resource group?

**Comment by basztech** [comment]
No resources have been created in that resource group.

**Comment by landonpierce** [comment]
Hmm, it looks like that tenant name has been taken. Does it exist maybe in another resource group or subscription? Or did you create it at one point and then delete it? B2C tenants are notoriously difficult to delete once they've been created :).

Can you try picking a different name to double check this theory? We're working on adding a check to the script to warn you beforehand, but in the meantime, you can check the name in the Azure portal first. 

![image](https://user-images.githubusercontent.com/93268703/192376381-5719c6ef-7ab8-4a84-9f12-5d6c26538021.png)

**Comment by basztech** [comment]
But I do own that tenant. The script successfully created the resource group in the same tenant but not the resource. It seems that the az rest call to create the B2C resource does not work.

**Comment by basztech** [comment]
So this was not an issue with the code but with my understanding of the implmentation.
