### ISSUE TITLE
When a B2C tenant already exists that is not owned by the current user, the B2C Create script enters an infinite loop

### ISSUE THREAD

**Issue by landonpierce** [Azure/azure-saas#200]
**Describe the bug**

The B2C-Create powershell script does not check to see if the name has been taken first before attempting to create a new tenant. It does, however, check to see if the tenant exists inside the user's current resource group. What that means is that if the tenant already exists in that resource group, the script will proceed fine as the create operation is idempotent. If the tenant name is taken by another user (or exists in another RG or sub), however, the operation does not succeed but the creation script will wait forever until the tenant is created. 

We need to modify the check on line 332 of [B2C-Create.ps1](https://github.com/Azure/azure-saas/blob/main/src/Saas.Identity/Saas.IdentityProvider/scripts/B2C-Create.ps1#L331) to check for ALL tenants, not just the ones inside that particular RG.

**Comment by landonpierce** [comment]
Related to #199

**Comment by 1iveowl** [comment]
In version 1.2 the PowerShell scipt have been replaced with a bash script. The whole provisioning and deployment have been rewritten to improve the deployment experience.
