### ISSUE TITLE
Concurrent AzureRm and Az modules will cause failure

### ISSUE THREAD

**Issue by idusortus** [Azure/azure-saas#203]
### Using Docker image, proess repeated the following, with an error of 'Bad Request' until interrupted:

```
Creating B2C tenant ratnest...
*** B2C Tenant creation started. It can take a moment to complete.
Waiting for 30 seconds for B2C tenant creation...

```

### Using .\Saas.IdentityProvider\scripts\B2C-Create.ps1
```
Line |
1160 |  New-SaaSIdentityProvider
     |  ~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Connect-AzAccount' is not recognized as a name of a cmdlet, function,
     | script file, or executable program. Check the spelling of the name, or if a path
     | was included, verify that the path is correct and try again.
```

## Problem
Old machine, had concurrent AzureRm and Az installations.

## Solution
```
Uninstall-AzureRm
```

# Request

- Please improve the error message when running in Docker. 
- Add a note to documentation that AzureRm needs to be removed.

Thank you for this quickstart!

**Comment by 1iveowl** [comment]
In version 1.2 the deployment script have been redone from the groud up and the PowerShell script have been replaced with a bash script.
