### ISSUE TITLE
Azure CLI 2.46 introduces breaking changes

### ISSUE THREAD

**Issue by natelabo** [Azure/azure-saas#209]
Bicep deployment fails due to issues with parameters not being passed properly when utilizing Azure CLI version 2.46 (Latest Version)

To reproduce follow setup instructions in Identity Provider.

Resolved by downgrading version in Dockerfile. Replace the following line:

`    && curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`

With (Taken from Azure CLI installation script):

`   apt-transport-https \
    lsb-release \
    && sudo mkdir -p /etc/apt/keyrings \
    && curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null \
    && sudo chmod go+r /etc/apt/keyrings/microsoft.gpg \
    && AZ_REPO=$(lsb_release -cs) \
    && echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list \
    && sudo apt-get update \
    && sudo apt-get install azure-cli=2.45.0-1~jammy -y`

**Comment by natelabo** [comment]
More info:

https://github.com/Azure/azure-cli/issues/25710

**Comment by 1iveowl** [comment]
Thanks @natelabo. Will take a look at it.

**Comment by 1iveowl** [comment]
A temporary work-around have been implemented with PR #211. 

The issues looks like an issue with Az CLI 2.46 and we will monitor this to see if we can remove the work-around at a later time.
