### ISSUE TITLE
Unknown Configuration: SaasAuthorization

### ISSUE THREAD

**Issue by natelabo** [Azure/azure-saas#210]
After running through setup procedure and attempting to deploy/test the Admin Service / API locally. Receiving build error:

An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.Extensions.Configuration.Abstractions.dll
Section 'SaasAuthorization' not found in configuration.

It looks like this may have been in introduced in recent permissions updates. I don't quite know what the configuration was supposed to be pointing at or looking for. Not able to move forward with testing.

**Comment by 1iveowl** [comment]
Thanks @natelabo. Will take a look at it.

**Comment by 1iveowl** [comment]
Thank you for reporting this issue. It has been fixed in PR #211. 

You will have to re-run the provisioning script for Saas.Admin: https://github.com/Azure/azure-saas/blob/main/src/Saas.Admin/deployment/run.sh

**Comment by natelabo** [comment]
@1iveowl Thanks for the quick response! I'll give this a go a little later today. Really appreciate the quickstart as well. This is very cool stuff!

**Comment by 1iveowl** [comment]
You are welcome. Please do let us know if you run into other challenges or have other feedback. Thanks
