### ISSUE TITLE
Update GCM to detect when it is running in a CI environment and use the appropriate token(s) for authentication. For the initial iteration, this effort will be scoped to GitHub and Azure DevOps.

### ISSUE THREAD

**Issue by Muradahmadbarakat** [Azure/azure-saas#227]
Update GCM to detect when it is running in a CI environment and use the appropriate token(s) for authentication. For the initial iteration, this effort will be scoped to GitHub and Azure DevOps.

_Originally posted by @ldennington in https://github.com/git-ecosystem/git-credential-manager/issues/1271_

**Comment by 1iveowl** [comment]
Could you add some more context please? 

What is the issue you are facing? Or are you making a request for an update?
