### ISSUE TITLE
Allow non-root Linux users to do a deployment from their machine

### ISSUE THREAD

**Issue by chgeuer** [Azure/azure-saas#236]
**Is your feature request related to a problem? Please describe.**

After running `src/Saas.Identity/Saas.IdentityProvider/deployment/run.sh`, the user's home directory contains an `~/asdk/.cache/.../` folder owned by `root.root`. 

**Describe the solution you'd like**

It would be good if the whole setup experience on the user's computer could run without the user being able to `sudo`.

```shell
chgeuer@beam:~/asdk/.cache/asdk-usr-b2c-hbtt$ ls -als
total 20
4 drwxr-xr-x 2 root    root 4096 Aug 23 14:36 .
4 drwxr-xr-x 3 chgeuer root 4096 Aug 23 14:36 ..
4 -rw-r--r-- 1 root    root  354 Aug 23 14:36 azureProfile.json
8 -rw------- 1 root    root 7632 Aug 23 14:36 msal_token_cache.json
```

Certainly going through the `.../*.sh` files and checking where we're calling `sudo`.

**Comment by 1iveowl** [comment]
Fix implemented with PR #235
