### ISSUE TITLE
Deployment with wrong SKU - PremiumP1 instead of Standard

### ISSUE THREAD

**Issue by leo-schick** [Azure/azure-saas#256]
**Describe the bug**
I followed the guideline [Deploying the Identity Foundation Services](https://github.com/Azure/azure-saas/tree/main/src/Saas.Identity/Saas.IdentityProvider) and changed during the inital setup the SKU for azureb2c in the `config.json` from `PremiumP1` to `Standard`, as the documentation tells is possible. But the deployed SKU of the Azure AD B2C tenant is `PremiumP1`, not `Standard`.

**To Reproduce**
1. Go to [Deploying the Identity Foundation Services](https://github.com/Azure/azure-saas/tree/main/src/Saas.Identity/Saas.IdentityProvider)
2. Follow the guide until [Running the script the first time](https://github.com/Azure/azure-saas/tree/main/src/Saas.Identity/Saas.IdentityProvider#running-the-script-the-first-time)
3. edit the `config.json` file and change `$.initConfig.azureb2c.skuName` from `PremiumP1` to Standard`
4. run the `./run.sh` script again
5. take a look at the SKU at the newly deployed Azure AD B2B Tenant

**Expected behavior**
The SKU should be `Standard`, but it is `PremiumP1`.

**Screenshots**
![image](https://github.com/Azure/azure-saas/assets/67712864/dd198f1a-c9e7-47f5-8e9d-d0e8d02224d3)
![image](https://github.com/Azure/azure-saas/assets/67712864/1fb50e7e-ee11-4b08-8a65-12df05bb82f5)

**Desktop (please complete the following information):**
 - OS: Windows with WSL Debian
 - Browser Chrome
 - Version / not required

**Comment by leo-schick** [comment]
I guess that the service plan "Standard" has been deleted and is automatically mapped by Azure to PremiumP1. If that is the case, the comment should be changed to not include `Standard` but only `PremiumP1` and `PremiumP2`.

**Comment by 1iveowl** [comment]
Thanks for reporting this @leo-schick. 

Indeed it looks like the `Standard` SKU is no longer available and that the comment needs to be updated.  

https://azure.microsoft.com/en-us/pricing/details/active-directory-external-identities/
