### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by wenms1** [Azure/azure-saas#34]
HI team,

glad to see MS starts focusing on this area. Keen to see more and often updates soon. 

Thanks,

Wen

**Comment by nickpinheiro** [comment]
Hi Wen!

Thank you very much for your comment.  Yes, there are many updates in flight and a long roadmap of upcoming features.  Be sure to also subscribe to the mailing list for the latest information and documentation:  https://www.onsubscriber.com/azuresaas 

- Nick
