### ISSUE TITLE
Web App Exceptions: An error occured while processing your request.

### ISSUE THREAD

**Issue by Zimmergren** [Azure/azure-saas#47]
Hi,

I wanted to take this kit for a spin to see how the deployment and dev-QA-prod lifecycle would work. 
Unfortunately, as soon as I've deployed it, the web app fails to register or sign in new members: 

![image](https://user-images.githubusercontent.com/4071728/135039611-ef45b11c-c763-4908-ba69-424506aefb69.png)

Are there any post-deployment steps that are required to mitigate this, or did we encounter a new bug? 

I haven't drilled down into the errors more than this; I just noticed this happening on two new deployments - so something seems to be amiss. I just wanted to bring this to your attention if you can fix it to avoid others having the same issue.

Thanks.

**Comment by nickpinheiro** [comment]
Hi @Zimmergren.  Thank you for submitting this issue.  This is actually due to an integration that we are working on in preparation for the MVP of the ASDK.  It is logged and currently being worked on. Thank you again!

**Comment by Zimmergren** [comment]
Hey @nickpinheiro,

Thanks for the insights. Is there an estimate or roadmap for when the MVP will be ready? Are we talking weeks, months, or next year?

**Comment by nickpinheiro** [comment]
Hey Tobias,

Absolutely.  We are currently working towards releasing the v1.0 of the ASKD in approximately one month.  Please be sure to subscribe at https://www.azuresaas.net as we will sending all release communications to the mailing list.  Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Zimmergren** [comment]
Great, thanks for the update.
