### ISSUE TITLE
"Deploy to Azure" failing

### ISSUE THREAD

**Issue by nhambayi** [Azure/azure-saas#75]
After clicking the "Deploy to Azure" button on the Azure SAAS DK site and providing the required information the deployment fails. This has happened with both paid and unpaid subscriptions.

DEPLOYMENT.OPERATIONS.JSON
[
  {
    "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/Microsoft.Template-20211214084404/operations/EE9CDC6B970B75D8",
    "operationId": "EE9CDC6B970B75D8",
    "properties": {
      "provisioningOperation": "Create",
      "provisioningState": "Failed",
      "timestamp": "2021-12-14T16:45:57.5132203Z",
      "duration": "PT1M7.6887762S",
      "trackingId": "1f9601ef-0f72-4284-b130-e1f042591e04",
      "serviceRequestId": "33ac6f8b-2303-4c88-88b1-1b578d211e50",
      "statusCode": "Conflict",
      "statusMessage": {
        "status": "Failed",
        "error": {
          "code": "DeploymentFailed",
          "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
          "details": [
            {
              "code": "Conflict",
              "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"ServiceUnavailable\",\r\n        \"message\": \"Database account creation failed. Operation Id: 8afe70e7-59b4-4211-bbe9-305c659b9f25, Error : Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.\\r\\nActivityId: 022e0839-12fd-43ec-839e-54612b355428, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0\"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
          ]
        }
      },
      "targetResource": {
        "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/deployCosmosDb",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "deployCosmosDb"
      }
    }
  },
  {
    "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/Microsoft.Template-20211214084404/operations/2949AFE5D6857534",
    "operationId": "2949AFE5D6857534",
    "properties": {
      "provisioningOperation": "Create",
      "provisioningState": "Failed",
      "timestamp": "2021-12-14T16:45:24.6937828Z",
      "duration": "PT34.8693387S",
      "trackingId": "7f25a3f0-2d38-469b-8c4a-4b4b3a454656",
      "serviceRequestId": "4863f9c7-5e55-4dd2-8965-9b40baffcb2c",
      "statusCode": "Conflict",
      "statusMessage": {
        "status": "Failed",
        "error": {
          "code": "DeploymentFailed",
          "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
          "details": [
            {
              "code": "Conflict",
              "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"ProvisioningDisabled\",\r\n        \"message\": \"Subscriptions are restricted from provisioning in this region. Please choose a different region. For exceptions to this rule please open a support request with Issue type of 'Service and subscription limits'. See https://docs.microsoft.com/en-us/azure/sql-database/quota-increase-request for more details.\"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
          ]
        }
      },
      "targetResource": {
        "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/deploySql",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "deploySql"
      }
    }
  }
]

DEPLOYMENT.JSON
{
  "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/Microsoft.Template-20211214084404",
  "name": "Microsoft.Template-20211214084404",
  "type": "Microsoft.Resources/deployments",
  "tags": {
    "marketplaceItemId": "Microsoft.Template"
  },
  "properties": {
    "templateLink": {
      "uri": "https://raw.githubusercontent.com/Azure/azure-saas/main/src/Saas.Deployment/Saas.Deployment.Root/azuredeploy.json",
      "contentVersion": "1.0.0.0"
    },
    "templateHash": "11589629160719704561",
    "parameters": {
      "saasProviderName": {
        "type": "String",
        "value": "vorobote"
      },
      "saasEnvironment": {
        "type": "String",
        "value": "dev"
      },
      "saasLocation": {
        "type": "String",
        "value": "westus3"
      },
      "saasInstanceNumber": {
        "type": "String",
        "value": "004"
      },
      "cosmosDbAccountName": {
        "type": "String",
        "value": "cosmos-vorobote-dev-004"
      },
      "cosmosDbDatabaseName": {
        "type": "String",
        "value": "cosmos-vorobote-dev-004"
      },
      "sqlAdministratorLogin": {
        "type": "String",
        "value": "vorboteadmin"
      },
      "sqlAdministratorLoginPassword": {
        "type": "SecureString"
      },
      "sqlServerName": {
        "type": "String",
        "value": "sql-vorobote-dev-004"
      },
      "sqlElasticPoolName": {
        "type": "String",
        "value": "sql-elasticpool-vorobote-dev-004"
      },
      "sqlEdition": {
        "type": "String",
        "value": "Basic"
      },
      "sqlElasticPoolCapacity": {
        "type": "Int",
        "value": 50
      },
      "sqlDatabaseCapacityMax": {
        "type": "Int",
        "value": 5
      }
    },
    "mode": "Incremental",
    "debugSetting": {
      "detailLevel": "None"
    },
    "provisioningState": "Failed",
    "timestamp": "2021-12-14T16:45:58.4844086Z",
    "duration": "PT1M9.4330677S",
    "correlationId": "6d040372-807f-4cfb-b4ad-e4beff8f5ecb",
    "providers": [
      {
        "namespace": "Microsoft.Resources",
        "resourceTypes": [
          {
            "resourceType": "deployments",
            "locations": [
              null
            ]
          }
        ]
      }
    ],
    "dependencies": [
      {
        "dependsOn": [
          {
            "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/deployCosmosDb",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "deployCosmosDb"
          },
          {
            "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/deploySql",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "deploySql"
          }
        ],
        "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/deployProviderWebApp",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "deployProviderWebApp"
      },
      {
        "dependsOn": [
          {
            "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/deploySql",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "deploySql"
          },
          {
            "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/deployProviderWebApp",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "deployProviderWebApp"
          }
        ],
        "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/deployOnboardingApiApp",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "deployOnboardingApiApp"
      },
      {
        "dependsOn": [
          {
            "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/deployCosmosDb",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "deployCosmosDb"
          },
          {
            "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/deploySql",
            "resourceType": "Microsoft.Resources/deployments",
            "resourceName": "deploySql"
          }
        ],
        "id": "/subscriptions/730bfc87-e487-4637-8f1a-85b39255ff53/resourceGroups/vorobte4/providers/Microsoft.Resources/deployments/deployAdminWebApp",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "deployAdminWebApp"
      }
    ],
    "error": {
      "code": "DeploymentFailed",
      "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
      "details": [
        {
          "code": "DeploymentFailed",
          "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details."
        },
        {
          "code": "DeploymentFailed",
          "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details."
        }
      ]
    },
    "validationLevel": "Template"
  }
}

**Comment by nickpinheiro** [comment]
Hi @nhambayi.  The 'Conflict' error you received above is not due to the deployment but due to the region you were attempting to deploy in.  The conflict message states 'Subscriptions are restricted from provisioning in this region. Please choose a different region. For exceptions to this rule please open a support request with Issue type of 'Service and subscription limits.'  Try a different region for the deployment and that will resolve this.

**Comment by nhambayi** [comment]
Thank you, Nick. I'm trying out the deployment after having attended your talk on it at Dev Intersections. After having failed West, West 2, and West 3 I assumed that error was a red herring and I opened the issue. But I now have been able to deploy it to North Central.

To help me plan future deployments, is there a way I can know up front where I can deploy my resources without hitting limits.

**Comment by nickpinheiro** [comment]
I've been seeing this in the last week or two as well in regards to specific regions.  I'll look deeper into it and will let you know what I find out.
