### ISSUE TITLE
Admin portal gives 500 Error

### ISSUE THREAD

**Issue by aquibchiniwala** [Azure/azure-saas#76]
Hello,
I deployed the template to Azure and the admin portal is not working. It returns Http 500 error.
Also, I feel the deployment template is incomplete as it doesn't deploy any application gateway as mentioned in the reference architecture.

**Comment by nickpinheiro** [comment]
Hello @aquibchiniwala,

Yes, as the ASDK is in public preview not all resources are included in the deployment yet.

The Admin Web App uses Azure AD for authentication and thus you will need to add your Azure AD information into your appsettings.json or in configuration in the App Service.  This will be included in our upcoming docs.

  "AzureAd": {
    "Instance": "",
    "Domain": "",
    "TenantId": "",
    "ClientId": "",
    "CallbackPath": ""
  }
